### ISSUE TITLE
Stairs not building in DOOM2 map 27

### ISSUE THREAD

**Issue by RamonUnch** [viti95/FastDoom#107] opened 2022-10-03 18:39 UTC
Since 51c1539 the stairs in doom2 map 27 no longer build.
You can find those stairs at coordinates: x=-1350, Y=528
The stairs are supposed to build like that:
![image](https://user-images.githubusercontent.com/74856804/193652875-3e09696c-589d-4f7b-8687-3cf1e2326d49.png)

This also cause a desync in any lv27 max demo.
Maybe there is a problem with the hash table.
Again a Killough patch.

**Comment by viti95** [comment] 2022-10-03 19:11
Sigh, checked and confirmed that it fails. So again I'm going to revert it until we find what's wrong.

**Comment by RamonUnch** [comment] 2022-10-03 21:02
Well I think the reason is that the switch (linedef 610) raises stairs from sector 15 as well as sector 20 (tag 26). In the end only stairs from sector 15 gets raised.

**Comment by RamonUnch** [comment] 2022-10-03 22:01
I can make two doors open with the same switch but not two stairs building with the same switch. I guess this is specific to because `EV_BuildStairs`.

**Comment by viti95** [comment] 2022-10-17 22:57
I'm closing this issue as the problem was fixed 😄. Thanks @RamonUnch !!

**Closed by viti95** 2022-10-17 22:57 UTC
Labels: bug, help wanted
